### ISSUE TITLE
wfs-1.1.0-Basic-GetFeature-tc5 test failing

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wfs11#90]
This is the only test case that is failing in my server. I'm running using OGC teamengine service.
error log shows 
`2020/04/06-18:16:57 ERROR
Test Name : wfs:wfs-1.1.0-Basic-GetFeature-tc5 type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public static org.w3c.dom.Node org.opengis.cite.wfs11.GetFeatureTestExtension.findFeatureTypeAndPropertyName(org.w3c.dom.Node) throws java.lang.Exception}: Extension function requires a single DOM Node; supplied value contains 3 nodes
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:600)
	at com.occamlab.te.TECore.executeTest(TECore.java:811)
	at com.occamlab.te.TECore.reexecute_test(TECore.java:371)
	at com.occamlab.te.TECore.execute(TECore.java:285)
	at com.occamlab.te.TECore.run(TECore.java:2403)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.sf.saxon.trans.XPathException: Error in call to extension function {public static org.w3c.dom.Node org.opengis.cite.wfs11.GetFeatureTestExtension.findFeatureTypeAndPropertyName(org.w3c.dom.Node) throws java.lang.Exception}: Extension function requires a single DOM Node; supplied value contains 3 nodes
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:151)
	at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:372)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	... 6 more`

here is the capabilities link you can use to see what is happening http://150.136.177.253:8000/oraclespatial/wfs/wfs?service=WFS&version=1.1.0&request=GetCapabilities
I don't know that is wrong.

**Comment by dstenger** [comment]
Thank you for reporting,
@keshav-nangare Can you please take a look at the reported behavior?

**Comment by keshav-nangare** [comment]
@coim32 

The above-provided service is not working, can you please provide another service?

**Comment by coim32** [comment]
that server is working now

**Comment by keshav-nangare** [comment]
@coim32  Thanks for making service available.

I tried to reproduce the issue using this service but found a different failure.
```
Message d123e9248_1:
   FAILURE: WFS does not provide data to use in this test 
                        (a feature type with a simple property (string, integer, double, decimal) and data for this property)
```
I debugged this issue and found the problem with `app` and `n2` prefixes, so while processing the response of GetFeature request with FeatureType so Xpath is not getting evaluated with n2 prefix and the method `findFeatureTypeAndPropertyName` returns null value so it is throwing above error.

You can see below workaround:
GetFeature request with FeatureType
http://150.136.177.253:8000/oraclespatial/wfs/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=app:AggregateGeoFeature&namespace=xmlns(app=http://cite.opengeospatial.org/gmlsf)

XPath which is trying to evaluate for above response 
```
//wfs:FeatureCollection/gml:featureMember/n2:AggregateGeoFeature/n2:description | //wfs:FeatureCollection/gml:featureMembers/n2:AggregateGeoFeature/n2:description
//wfs:FeatureCollection/gml:featureMember/n2:AggregateGeoFeature/n2:name | //wfs:FeatureCollection/gml:featureMembers/n2:AggregateGeoFeature/n2:name
```
Can you please look into this issue? 

Can you please provide steps/workaround to reproduce this issue?

**Comment by dstenger** [comment]
As keshav-nangare already stated, Java method `findFeatureTypeAndPropertyName` returns null instead of a result leading to the reported behavior.
This can be reproduced by test in class `GetFeatureTestExtensionIT`.

The root cause of the failing test is that all properties are in namespace `http://www.opengis.net/gml` as you can see in view-source:http://150.136.177.253:8000/oraclespatial/wfs/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=app:AggregateGeoFeature&namespace=xmlns(app=http://cite.opengeospatial.org/gmlsf).
E.g.:
```
...

         <sf:doubleProperty xmlns:sf="http://www.opengis.net/gml">2012.78</sf:doubleProperty>
         <sf:strProperty xmlns:sf="http://www.opengis.net/gml">Ma quande lingues coalesce, li grammatica del resultant lingue es plu simplic e regulari quam ti del coalescent lingues. Li nov lingua franca va esser plu simplic e regulari quam li existent Europan lingues.</sf:strProperty>
         <sf:featureCode xmlns:sf="http://www.opengis.net/gml">BK030</sf:featureCode>
      </app:AggregateGeoFeature>
...
```
However, DescribeFeatureType response (view-source:http://150.136.177.253:8000/oraclespatial/wfs/wfs?service=WFS&version=1.1.0&request=DescribeFeatureType) expects them in namespace `http://cite.opengeospatial.org/gmlsf`.

Thus, this failure is correct and the service implementation causes the error.

@coim32 Can you please confirm if you are able to fix this error and close this issue afterwards?

**Comment by coim32** [comment]
that was the problem, thanks for you help
